name: 🐛 Report Bug
description: Report a broken link or error in the documentation
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please provide details below.
  
  - type: dropdown
    id: bug-type
    attributes:
      label: Issue Type
      options:
        - Broken Link
        - Incorrect Information
        - Formatting Error
        - Other
    validations:
      required: true
  
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the issue? (file name and section)
      placeholder: e.g., README.md - Browser Tools section
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: What's wrong?
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful